version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3001'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    expose:
      - '3001'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./service_nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
